const GET_PROGRAMS_REQUEST = 'GET_PROGRAMS_REQUEST';
const GET_PROGRAMS_SUCCESS = 'GET_PROGRAMS_SUCCESS';
const GET_PROGRAMS_FAILURE = 'GET_PROGRAMS_FAILURE';
const CREATE_PROGRAM_REQUEST = 'CREATE_PROGRAM_REQUEST';
const CREATE_PROGRAM_SUCCESS = 'CREATE_PROGRAM_SUCCESS';
const CREATE_PROGRAM_FAILURE = 'CREATE_PROGRAM_FAILURE';

export default {
	GET_PROGRAMS_REQUEST,
	GET_PROGRAMS_SUCCESS,
	GET_PROGRAMS_FAILURE,
	CREATE_PROGRAM_REQUEST,
	CREATE_PROGRAM_SUCCESS,
	CREATE_PROGRAM_FAILURE,
}
