const GET_MUSCLE_GROUPS_REQUEST = "GET_MUSCLE_GROUPS_REQUEST";
const GET_MUSCLE_GROUPS_SUCCESS = "GET_MUSCLE_GROUPS_SUCCESS";
const GET_MUSCLE_GROUPS_FAILURE = "GET_MUSCLE_GROUPS_FAILURE";
const CREATE_MUSCLE_GROUP_REQUEST = "CREATE_MUSCLE_GROUP_REQUEST";
const CREATE_MUSCLE_GROUP_SUCCESS = "CREATE_MUSCLE_GROUP_SUCCESS";
const CREATE_MUSCLE_GROUP_FAILURE = "CREATE_MUSCLE_GROUP_FAILURE";
const UPDATE_MUSCLE_GROUP_REQUEST = "UPDATE_MUSCLE_GROUP_REQUEST";
const UPDATE_MUSCLE_GROUP_SUCCESS = "UPDATE_MUSCLE_GROUP_SUCCESS";
const UPDATE_MUSCLE_GROUP_FAILURE = "UPDATE_MUSCLE_GROUP_FAILURE";
const DELETE_MUSCLE_GROUP_REQUEST = "DELETE_MUSCLE_GROUP_REQUEST";
const DELETE_MUSCLE_GROUP_SUCCESS = "DELETE_MUSCLE_GROUP_SUCCESS";
const DELETE_MUSCLE_GROUP_FAILURE = "DELETE_MUSCLE_GROUP_FAILURE";

export default {
  GET_MUSCLE_GROUPS_REQUEST,
	GET_MUSCLE_GROUPS_SUCCESS,
	GET_MUSCLE_GROUPS_FAILURE,
	CREATE_MUSCLE_GROUP_REQUEST,
	CREATE_MUSCLE_GROUP_SUCCESS,
	CREATE_MUSCLE_GROUP_FAILURE,
	UPDATE_MUSCLE_GROUP_REQUEST,
	UPDATE_MUSCLE_GROUP_SUCCESS,
	UPDATE_MUSCLE_GROUP_FAILURE,
	DELETE_MUSCLE_GROUP_REQUEST,
	DELETE_MUSCLE_GROUP_SUCCESS,
	DELETE_MUSCLE_GROUP_FAILURE,
}