const CREATE_SET_REQUEST = "CREATE_SET_REQUEST";
const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
const CREATE_SET_FAILURE = "CREATE_SET_FAILURE";
const GET_SET_REQUEST = "GET_SET_REQUEST";
const GET_SET_SUCCESS = "GET_SET_SUCCESS";
const GET_SET_FAILURE = "GET_SET_FAILURE";
const GET_SETS_REQUEST = "GET_SETS_REQUEST";
const GET_SETS_SUCCESS = "GET_SETS_SUCCESS";
const GET_SETS_FAILURE = "GET_SETS_FAILURE";
const UPDATE_SET_REQUEST = "UPDATE_SET_REQUEST";
const UPDATE_SET_SUCCESS = "UPDATE_SET_SUCCESS";
const UPDATE_SET_FAILURE = "UPDATE_SET_FAILURE";
const DELETE_SET_REQUEST = "DELETE_SET_REQUEST";
const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";
const DELETE_SET_FAILURE = "DELETE_SET_FAILURE";

export default {
  CREATE_SET_REQUEST,
	CREATE_SET_SUCCESS,
	CREATE_SET_FAILURE,
	GET_SET_REQUEST,
	GET_SET_SUCCESS,
	GET_SET_FAILURE,
	GET_SETS_REQUEST,
	GET_SETS_SUCCESS,
	GET_SETS_FAILURE,
	UPDATE_SET_REQUEST,
	UPDATE_SET_SUCCESS,
	UPDATE_SET_FAILURE,
	DELETE_SET_REQUEST,
	DELETE_SET_SUCCESS,
	DELETE_SET_FAILURE,
}