const GET_MUSCLE_GROUPS_REQUEST = "GET_MUSCLE_GROUPS_REQUEST";
const GET_MUSCLE_GROUPS_SUCCESS = "GET_MUSCLE_GROUPS_SUCCESS";
const GET_MUSCLE_GROUPS_FAILURE = "GET_MUSCLE_GROUPS_FAILURE";
const CREATE_MUSCLE_GROUPS_REQUEST = "CREATE_MUSCLE_GROUPS_REQUEST";
const CREATE_MUSCLE_GROUPS_SUCCESS = "CREATE_MUSCLE_GROUPS_SUCCESS";
const CREATE_MUSCLE_GROUPS_FAILURE = "CREATE_MUSCLE_GROUPS_FAILURE";
const UPDATE_MUSCLE_GROUPS_REQUEST = "UPDATE_MUSCLE_GROUPS_REQUEST";
const UPDATE_MUSCLE_GROUPS_SUCCESS = "UPDATE_MUSCLE_GROUPS_SUCCESS";
const UPDATE_MUSCLE_GROUPS_FAILURE = "UPDATE_MUSCLE_GROUPS_FAILURE";
const DELETE_MUSCLE_GROUPS_REQUEST = "DELETE_MUSCLE_GROUPS_REQUEST";
const DELETE_MUSCLE_GROUPS_SUCCESS = "DELETE_MUSCLE_GROUPS_SUCCESS";
const DELETE_MUSCLE_GROUPS_FAILURE = "DELETE_MUSCLE_GROUPS_FAILURE";
const GET_MUSCLES_REQUEST = "GET_MUSCLES_REQUEST";
const GET_MUSCLES_SUCCESS = "GET_MUSCLES_SUCCESS";
const GET_MUSCLES_FAILURE = "GET_MUSCLES_FAILURE";
const CREATE_MUSCLE_REQUEST = "CREATE_MUSCLE_REQUEST";
const CREATE_MUSCLE_SUCCESS = "CREATE_MUSCLE_SUCCESS";
const CREATE_MUSCLE_FAILURE = "CREATE_MUSCLE_FAILURE";
const UPDATE_MUSCLE_REQUEST = "UPDATE_MUSCLE_REQUEST";
const UPDATE_MUSCLE_SUCCESS = "UPDATE_MUSCLE_SUCCESS";
const UPDATE_MUSCLE_FAILURE = "UPDATE_MUSCLE_FAILURE";
const DELETE_MUSCLES_REQUEST = "DELETE_MUSCLES_REQUEST";
const DELETE_MUSCLES_SUCCESS = "DELETE_MUSCLES_SUCCESS";
const DELETE_MUSCLES_FAILURE = "DELETE_MUSCLES_FAILURE";
const GET_EXERCISES_REQUEST = "GET_EXERCISES_REQUEST";
const GET_EXERCISES_SUCCESS = "GET_EXERCISES_SUCCESS";
const GET_EXERCISES_FAILURE = "GET_EXERCISES_FAILURE";
const CREATE_EXERCISE_REQUEST = "CREATE_EXERCISE_REQUEST";
const CREATE_EXERCISE_SUCCESS = "CREATE_EXERCISE_SUCCESS";
const CREATE_EXERCISE_FAILURE = "CREATE_EXERCISE_FAILURE";
const UPDATE_EXERCISE_REQUEST = "UPDATE_EXERCISE_REQUEST";
const UPDATE_EXERCISE_SUCCESS = "UPDATE_EXERCISE_SUCCESS";
const UPDATE_EXERCISE_FAILURE = "UPDATE_EXERCISE_FAILURE";
const DELETE_EXERCISE_REQUEST = "DELETE_EXERCISE_REQUEST";
const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";
const DELETE_EXERCISE_FAILURE = "DELETE_EXERCISE_FAILURE";
const CREATE_SET_REQUEST = "CREATE_SET_REQUEST";
const CREATE_SET_SUCCESS = "CREATE_SET_SUCCESS";
const CREATE_SET_FAILURE = "CREATE_SET_FAILURE";
const GET_SET_REQUEST = "GET_SET_REQUEST";
const GET_SET_SUCCESS = "GET_SET_SUCCESS";
const GET_SET_FAILURE = "GET_SET_FAILURE";
const GET_SETS_REQUEST = "GET_SETS_REQUEST";
const GET_SETS_SUCCESS = "GET_SETS_SUCCESS";
const GET_SETS_FAILURE = "GET_SETS_FAILURE";
const UPDATE_SET_REQUEST = "UPDATE_SET_REQUEST";
const UPDATE_SET_SUCCESS = "UPDATE_SET_SUCCESS";
const UPDATE_SET_FAILURE = "UPDATE_SET_FAILURE";
const DELETE_SET_REQUEST = "DELETE_SET_REQUEST";
const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";
const DELETE_SET_FAILURE = "DELETE_SET_FAILURE";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAILURE = "LOGOUT_FAILURE";
const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILURE = "GET_USER_FAILURE";
const START_WORKOUT_REQUEST = "START_WORKOUT_REQUEST";
const START_WORKOUT_SUCCESS = "START_WORKOUT_SUCCESS";
const START_WORKOUT_FAILURE = "START_WORKOUT_FAILURE";
const CONTINUE_WORKOUT_REQUEST = "CONTINUE_WORKOUT_REQUEST";
const CONTINUE_WORKOUT_SUCCESS = "CONTINUE_WORKOUT_SUCCESS";
const CONTINUE_WORKOUT_FAILURE = "CONTINUE_WORKOUT_FAILURE";
const CLEAR_SET = "CLEAR_SET";
const GET_WORKOUTS_REQUEST = "GET_WORKOUTS_REQUEST";
const GET_WORKOUTS_SUCCESS = "GET_WORKOUTS_SUCCESS";
const GET_WORKOUTS_FAILURE = "GET_WORKOUTS_FAILURE";
const GET_WORKOUT_REQUEST = "GET_WORKOUT_REQUEST";
const GET_WORKOUT_SUCCESS = "GET_WORKOUT_SUCCESS";
const GET_WORKOUT_FAILURE = "GET_WORKOUT_FAILURE";

export default {
	GET_MUSCLE_GROUPS_REQUEST,
	GET_MUSCLE_GROUPS_SUCCESS,
	GET_MUSCLE_GROUPS_FAILURE,
	CREATE_MUSCLE_GROUPS_REQUEST,
	CREATE_MUSCLE_GROUPS_SUCCESS,
	CREATE_MUSCLE_GROUPS_FAILURE,
	UPDATE_MUSCLE_GROUPS_REQUEST,
	UPDATE_MUSCLE_GROUPS_SUCCESS,
	UPDATE_MUSCLE_GROUPS_FAILURE,
	DELETE_MUSCLE_GROUPS_REQUEST,
	DELETE_MUSCLE_GROUPS_SUCCESS,
	DELETE_MUSCLE_GROUPS_FAILURE,
	GET_MUSCLES_REQUEST,
	GET_MUSCLES_SUCCESS,
	GET_MUSCLES_FAILURE,
	CREATE_MUSCLE_REQUEST,
	CREATE_MUSCLE_SUCCESS,
	CREATE_MUSCLE_FAILURE,
	UPDATE_MUSCLE_REQUEST,
	UPDATE_MUSCLE_SUCCESS,
	UPDATE_MUSCLE_FAILURE,
	DELETE_MUSCLES_REQUEST,
	DELETE_MUSCLES_SUCCESS,
	DELETE_MUSCLES_FAILURE,
	GET_EXERCISES_REQUEST,
	GET_EXERCISES_SUCCESS,
	GET_EXERCISES_FAILURE,
	CREATE_EXERCISE_REQUEST,
	CREATE_EXERCISE_SUCCESS,
	CREATE_EXERCISE_FAILURE,
	UPDATE_EXERCISE_REQUEST,
	UPDATE_EXERCISE_SUCCESS,
	UPDATE_EXERCISE_FAILURE,
	DELETE_EXERCISE_REQUEST,
	DELETE_EXERCISE_SUCCESS,
	DELETE_EXERCISE_FAILURE,
	CREATE_SET_REQUEST,
	CREATE_SET_SUCCESS,
	CREATE_SET_FAILURE,
	GET_SET_REQUEST,
	GET_SET_SUCCESS,
	GET_SET_FAILURE,
	GET_SETS_REQUEST,
	GET_SETS_SUCCESS,
	GET_SETS_FAILURE,
	UPDATE_SET_REQUEST,
	UPDATE_SET_SUCCESS,
	UPDATE_SET_FAILURE,
	DELETE_SET_REQUEST,
	DELETE_SET_SUCCESS,
	DELETE_SET_FAILURE,
	LOGIN_REQUEST,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	LOGOUT_REQUEST,
	LOGOUT_SUCCESS,
	LOGOUT_FAILURE,
	GET_USER_REQUEST,
	GET_USER_SUCCESS,
	GET_USER_FAILURE,
	START_WORKOUT_REQUEST,
	START_WORKOUT_SUCCESS,
	START_WORKOUT_FAILURE,
	CONTINUE_WORKOUT_REQUEST,
	CONTINUE_WORKOUT_SUCCESS,
	CONTINUE_WORKOUT_FAILURE,
	CLEAR_SET,
	GET_WORKOUTS_REQUEST,
	GET_WORKOUTS_SUCCESS,
	GET_WORKOUTS_FAILURE,
	GET_WORKOUT_REQUEST,
	GET_WORKOUT_SUCCESS,
	GET_WORKOUT_FAILURE,
}
