const GET_MUSCLES_REQUEST = "GET_MUSCLES_REQUEST";
const GET_MUSCLES_SUCCESS = "GET_MUSCLES_SUCCESS";
const GET_MUSCLES_FAILURE = "GET_MUSCLES_FAILURE";
const CREATE_MUSCLE_REQUEST = "CREATE_MUSCLE_REQUEST";
const CREATE_MUSCLE_SUCCESS = "CREATE_MUSCLE_SUCCESS";
const CREATE_MUSCLE_FAILURE = "CREATE_MUSCLE_FAILURE";
const UPDATE_MUSCLE_REQUEST = "UPDATE_MUSCLE_REQUEST";
const UPDATE_MUSCLE_SUCCESS = "UPDATE_MUSCLE_SUCCESS";
const UPDATE_MUSCLE_FAILURE = "UPDATE_MUSCLE_FAILURE";
const DELETE_MUSCLE_REQUEST = "DELETE_MUSCLE_REQUEST";
const DELETE_MUSCLE_SUCCESS = "DELETE_MUSCLE_SUCCESS";
const DELETE_MUSCLE_FAILURE = "DELETE_MUSCLE_FAILURE";

export default {
  GET_MUSCLES_REQUEST,
	GET_MUSCLES_SUCCESS,
	GET_MUSCLES_FAILURE,
	CREATE_MUSCLE_REQUEST,
	CREATE_MUSCLE_SUCCESS,
	CREATE_MUSCLE_FAILURE,
	UPDATE_MUSCLE_REQUEST,
	UPDATE_MUSCLE_SUCCESS,
	UPDATE_MUSCLE_FAILURE,
	DELETE_MUSCLE_REQUEST,
	DELETE_MUSCLE_SUCCESS,
	DELETE_MUSCLE_FAILURE,
}