const START_WORKOUT_REQUEST = "START_WORKOUT_REQUEST";
const START_WORKOUT_SUCCESS = "START_WORKOUT_SUCCESS";
const START_WORKOUT_FAILURE = "START_WORKOUT_FAILURE";
const CONTINUE_WORKOUT = "CONTINUE_WORKOUT";
const CLEAR_SET = "CLEAR_SET";
const GET_WORKOUTS_REQUEST = "GET_WORKOUTS_REQUEST";
const GET_WORKOUTS_SUCCESS = "GET_WORKOUTS_SUCCESS";
const GET_WORKOUTS_FAILURE = "GET_WORKOUTS_FAILURE";
const GET_WORKOUT_REQUEST = "GET_WORKOUT_REQUEST";
const GET_WORKOUT_SUCCESS = "GET_WORKOUT_SUCCESS";
const GET_WORKOUT_FAILURE = "GET_WORKOUT_FAILURE";
const GET_CURRENT_WORKOUT_REQUEST = "GET_CURRENT_WORKOUT_REQUEST";
const GET_CURRENT_WORKOUT_SUCCESS = "GET_CURRENT_WORKOUT_SUCCESS";
const GET_CURRENT_WORKOUT_FAILURE = "GET_CURRENT_WORKOUT_FAILURE";
const GET_SUGGESTION_REQUEST = "GET_SUGGESTION_REQUEST";
const GET_SUGGESTION_SUCCESS = "GET_SUGGESTION_SUCCESS";
const GET_SUGGESTION_FAILURE = "GET_SUGGESTION_FAILURE";
const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";
const CLEAR_WORKOUT = "CLEAR_WORKOUT";

export default {
  START_WORKOUT_REQUEST,
	START_WORKOUT_SUCCESS,
	START_WORKOUT_FAILURE,
	CONTINUE_WORKOUT,
	CLEAR_SET,
	GET_WORKOUTS_REQUEST,
	GET_WORKOUTS_SUCCESS,
	GET_WORKOUTS_FAILURE,
	GET_WORKOUT_REQUEST,
	GET_WORKOUT_SUCCESS,
	GET_WORKOUT_FAILURE,
	GET_CURRENT_WORKOUT_REQUEST,
	GET_CURRENT_WORKOUT_SUCCESS,
	GET_CURRENT_WORKOUT_FAILURE,
	GET_SUGGESTION_REQUEST,
	GET_SUGGESTION_SUCCESS,
	GET_SUGGESTION_FAILURE,
	CLEAR_SUGGESTIONS,
	CLEAR_WORKOUT,
}