const GET_EXERCISES_REQUEST = "GET_EXERCISES_REQUEST";
const GET_EXERCISES_SUCCESS = "GET_EXERCISES_SUCCESS";
const GET_EXERCISES_FAILURE = "GET_EXERCISES_FAILURE";
const CREATE_EXERCISE_REQUEST = "CREATE_EXERCISE_REQUEST";
const CREATE_EXERCISE_SUCCESS = "CREATE_EXERCISE_SUCCESS";
const CREATE_EXERCISE_FAILURE = "CREATE_EXERCISE_FAILURE";
const UPDATE_EXERCISE_REQUEST = "UPDATE_EXERCISE_REQUEST";
const UPDATE_EXERCISE_SUCCESS = "UPDATE_EXERCISE_SUCCESS";
const UPDATE_EXERCISE_FAILURE = "UPDATE_EXERCISE_FAILURE";
const DELETE_EXERCISE_REQUEST = "DELETE_EXERCISE_REQUEST";
const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";
const DELETE_EXERCISE_FAILURE = "DELETE_EXERCISE_FAILURE";

export default {
  GET_EXERCISES_REQUEST,
	GET_EXERCISES_SUCCESS,
	GET_EXERCISES_FAILURE,
	CREATE_EXERCISE_REQUEST,
	CREATE_EXERCISE_SUCCESS,
	CREATE_EXERCISE_FAILURE,
	UPDATE_EXERCISE_REQUEST,
	UPDATE_EXERCISE_SUCCESS,
	UPDATE_EXERCISE_FAILURE,
	DELETE_EXERCISE_REQUEST,
	DELETE_EXERCISE_SUCCESS,
	DELETE_EXERCISE_FAILURE,
}